<a href="https://colab.research.google.com/github/zackyalgiffari/CathyGaisCountDataset/blob/main/Text_Mining_Gais_Cathculator.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

#GaisCathculator

Project Description:

This project aims to analyze the frequency of the word "gais" in the posts made by the X account N_CathyJKT48. The dataset consists of posts from Cathy's X account, and the goal is to count how many times the word "gais" appears in her posts. Additionally, the project calculates the total number of posts made by Cathy on X.

Author: @zacathy48

In [25]:
#Import library
import pandas as pd

In [26]:
#File path link

file_path1 = 'https://raw.githubusercontent.com/zackyalgiffari/CathyGaisCountDataset/main/CathyGais%208%20Maret%202024.csv'
file_path2 = 'https://raw.githubusercontent.com/zackyalgiffari/CathyGaisCountDataset/main/CathyGaiss%208%20Maret%202024.csv'
file_path3 = 'https://raw.githubusercontent.com/zackyalgiffari/CathyGaisCountDataset/main/CathyGaisss%208%20Maret%202024.csv'

# read first csv file
df1 = pd.read_csv(file_path1, delimiter=";")

# read second csv file
df2 = pd.read_csv(file_path2, delimiter=";")

# read third csv file
df3 = pd.read_csv(file_path3, delimiter=";")

# Combine dataframe
combined_df = pd.concat([df1, df2, df3], ignore_index=True)

# Save combined data to csv file
combined_df.to_csv('combined_file.csv', index=False)

In [27]:
#Display head of combined data
combined_df.head()

,created_at,id_str,full_text,quote_count,reply_count,retweet_count,favorite_count,lang,user_id_str,conversation_id_str,username,tweet_url
0,Wed Feb 28 15:37:40 +0000 2024,1762864652923662643,Gais,1,146,54,4554,lt,1586992742093103104,1762864652923662643,N_CathyJKT48,https://twitter.com/N_CathyJKT48/status/176286...
1,Sun Feb 25 04:36:15 +0000 2024,1761611036908757295,Buat ini perlu perjuangan Gais Yang pertama g...,4,66,77,4166,in,1586992742093103104,1761609638053863657,N_CathyJKT48,https://twitter.com/N_CathyJKT48/status/176161...
2,Fri Feb 23 15:28:53 +0000 2024,1761050502849323295,Gais sr nya besokkk yaw sambil otw theaterüòäü´∂üèª,6,141,55,4507,in,1586992742093103104,1761050502849323295,N_CathyJKT48,https://twitter.com/N_CathyJKT48/status/176105...
3,Mon Feb 19 07:16:57 +0000 2024,1759477153195081994,Gais,4,248,59,5454,lt,1586992742093103104,1759477153195081994,N_CathyJKT48,https://twitter.com/N_CathyJKT48/status/175947...
4,Sun Feb 18 18:14:10 +0000 2024,1759280159209971827,"Gais besokkk ya jadi nya mauu srrr ,hehe maaf ...",2,94,64,5046,in,1586992742093103104,1759280159209971827,N_CathyJKT48,https://twitter.com/N_CathyJKT48/status/175928...

In [28]:
# Display information of combined data
combined_df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 104 entries, 0 to 103
Data columns (total 12 columns):
 #   Column               Non-Null Count  Dtype
---  ------               --------------  -----
 0   created_at           104 non-null    object
 1   id_str               104 non-null    int64
 2   full_text            104 non-null    object
 3   quote_count          104 non-null    int64
 4   reply_count          104 non-null    int64
 5   retweet_count        104 non-null    int64
 6   favorite_count       104 non-null    int64
 7   lang                 104 non-null    object
 8   user_id_str          104 non-null    int64
 9   conversation_id_str  104 non-null    int64
 10  username             104 non-null    object
 11  tweet_url            104 non-null    object
dtypes: int64(7), object(5)
memory usage: 9.9+ KB

In [29]:
# Check for duplicated values based on 'id_str' column
duplicated_values = combined_df[combined_df.duplicated(subset=['id_str'])]
print(duplicated_values)

                         created_at               id_str  \
83   Sat Jan 21 15:55:38 +0000 2023  1616826864265498631
84   Tue Dec 20 14:59:51 +0000 2022  1605216416428199936
86   Tue Dec 20 14:59:51 +0000 2022  1605216416428199936
87   Fri Nov 10 05:01:47 +0000 2023  1722841963312103897
89   Wed Jun 14 10:22:16 +0000 2023  1668926822803980288
90   Thu Mar 02 06:15:39 +0000 2023  1631176423569502208
91   Sat Feb 25 03:44:22 +0000 2023  1629326409100558336
92   Thu Feb 23 13:46:37 +0000 2023  1628753194598932482
95   Sat Jan 21 15:55:38 +0000 2023  1616826864265498631
101  Thu Dec 29 09:23:08 +0000 2022  1608393168621539332
102  Tue Dec 20 14:59:51 +0000 2022  1605216416428199936

                                             full_text  quote_count  \
83   Ini part 2nya ya gais‚Ä¶ Jadi aku sama ci @Graci...            4
84   @Y_CynthiaJKT48 IYA GAISS,kita itu udah niat b...            1
86   @Y_CynthiaJKT48 IYA GAISS,kita itu udah niat b...            1
87               Okei aku sudah tau makasih ya gaiss üíó            0
89                                               Gaiss            3
90   Gaiss jaga kesehatan yaa cuacanya lagii gaa ba...            2
91   Gaiss mau tanya dong,apa yang membuat kalian i...            3
92   Gaiss kalian sukaa warna apaa,kalo aku suka wa...            0
95   Ini part 2nya ya gais‚Ä¶ Jadi aku sama ci @Graci...            4
101  Gaiss aku baru beli lato‚Äù dong,tapi ga tau car...            5
102  @Y_CynthiaJKT48 IYA GAISS,kita itu udah niat b...            1

     reply_count  retweet_count  favorite_count lang          user_id_str  \
83            64             33            1340   in  1586992742093103104
84            19             19            1311   in  1586992742093103104
86            19             19            1311   in  1586992742093103104
87            38             47            3800   in  1586992742093103104
89           282             34            3681   en  1586992742093103104
90            45             29            1367   in  1586992742093103104
91           111             26            1616   in  1586992742093103104
92            68             17            1250   in  1586992742093103104
95            64             33            1340   in  1586992742093103104
101          118             32            2308   in  1586992742093103104
102           19             19            1311   in  1586992742093103104

     conversation_id_str      username  \
83   1616826864265498631  N_CathyJKT48
84   1605210346733834242  N_CathyJKT48
86   1605210346733834242  N_CathyJKT48
87   1722841963312103897  N_CathyJKT48
89   1668926822803980288  N_CathyJKT48
90   1631176423569502208  N_CathyJKT48
91   1629326409100558336  N_CathyJKT48
92   1628753194598932482  N_CathyJKT48
95   1616826864265498631  N_CathyJKT48
101  1608393168621539332  N_CathyJKT48
102  1605210346733834242  N_CathyJKT48

                                             tweet_url
83   https://twitter.com/N_CathyJKT48/status/161682...
84   https://twitter.com/N_CathyJKT48/status/160521...
86   https://twitter.com/N_CathyJKT48/status/160521...
87   https://twitter.com/N_CathyJKT48/status/172284...
89   https://twitter.com/N_CathyJKT48/status/166892...
90   https://twitter.com/N_CathyJKT48/status/163117...
91   https://twitter.com/N_CathyJKT48/status/162932...
92   https://twitter.com/N_CathyJKT48/status/162875...
95   https://twitter.com/N_CathyJKT48/status/161682...
101  https://twitter.com/N_CathyJKT48/status/160839...
102  https://twitter.com/N_CathyJKT48/status/160521...

In [30]:
# Drop duplicated values
combined_df = combined_df.drop_duplicates()
combined_df.info()

<class 'pandas.core.frame.DataFrame'>
Int64Index: 96 entries, 0 to 103
Data columns (total 12 columns):
 #   Column               Non-Null Count  Dtype
---  ------               --------------  -----
 0   created_at           96 non-null     object
 1   id_str               96 non-null     int64
 2   full_text            96 non-null     object
 3   quote_count          96 non-null     int64
 4   reply_count          96 non-null     int64
 5   retweet_count        96 non-null     int64
 6   favorite_count       96 non-null     int64
 7   lang                 96 non-null     object
 8   user_id_str          96 non-null     int64
 9   conversation_id_str  96 non-null     int64
 10  username             96 non-null     object
 11  tweet_url            96 non-null     object
dtypes: int64(7), object(5)
memory usage: 9.8+ KB

In [31]:
# Perform feature engineering: convert 'full_text' to lowercase
combined_df['full_text'] = combined_df['full_text'].apply(lambda x: x.lower())

# Select specific columns for further analysis
selected_columns = ['created_at', 'id_str', 'full_text','tweet_url']
df = combined_df[selected_columns]
df.head()

<ipython-input-31-bd3e64bcb607>:2: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  combined_df['full_text'] = combined_df['full_text'].apply(lambda x: x.lower())

,created_at,id_str,full_text,tweet_url
0,Wed Feb 28 15:37:40 +0000 2024,1762864652923662643,gais,https://twitter.com/N_CathyJKT48/status/176286...
1,Sun Feb 25 04:36:15 +0000 2024,1761611036908757295,buat ini perlu perjuangan gais yang pertama g...,https://twitter.com/N_CathyJKT48/status/176161...
2,Fri Feb 23 15:28:53 +0000 2024,1761050502849323295,gais sr nya besokkk yaw sambil otw theaterüòäü´∂üèª,https://twitter.com/N_CathyJKT48/status/176105...
3,Mon Feb 19 07:16:57 +0000 2024,1759477153195081994,gais,https://twitter.com/N_CathyJKT48/status/175947...
4,Sun Feb 18 18:14:10 +0000 2024,1759280159209971827,"gais besokkk ya jadi nya mauu srrr ,hehe maaf ...",https://twitter.com/N_CathyJKT48/status/175928...

In [32]:
# Display information of selected data
df.info()

<class 'pandas.core.frame.DataFrame'>
Int64Index: 96 entries, 0 to 103
Data columns (total 4 columns):
 #   Column      Non-Null Count  Dtype
---  ------      --------------  -----
 0   created_at  96 non-null     object
 1   id_str      96 non-null     int64
 2   full_text   96 non-null     object
 3   tweet_url   96 non-null     object
dtypes: int64(1), object(3)
memory usage: 5.8+ KB

In [33]:
# Save selected data to Excel file
df.to_excel('FinalCathyGaisCounting.xlsx', index=False)

In [34]:
# Count occurrences of 'gais', 'gaiss', and 'gaisss' in 'full_text' column
df['Jumlah'] = df['full_text'].str.count(r'gais{1,3}\b')
total = df['Jumlah'].sum()

# Print total occurrences of the "Gais" words
print(f"Jumlah Kemunculan kata 'gais' di akun X N_CathyJKT48 sebanyak: {total},dari {jumlah_baris} post")

Jumlah Kemunculan kata 'gais' di akun X N_CathyJKT48 sebanyak: 102,dari 96 post

<ipython-input-34-b053bc48f00e>:2: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df['Jumlah'] = df['full_text'].str.count(r'gais{1,3}\b')